name: Deploy on hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on hosting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/j/jan555is/fintrack.space
            php8.3 artisan optimize:clear
            php8.3 artisan down
            git pull origin main
            php8.3 composer.phar install --optimize-autoloader
            php8.3 artisan migrate --force
            php8.3 artisan optimize
            php8.3 artisan config:cache
            php8.3 artisan event:cache
            php8.3 artisan route:cache
            php8.3 artisan view:cache
            php8.3 artisan up
